import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import User from '../../app/Models/User'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  public static environment = ['development']
  public async run () {
    await User.createMany([
      {
        email: 'example1@example.com',
        selectedProfileId: null,
        password: 'password1',
        secret: 'OOIRB5KJHL3CTDFT4ROS47ZFZXRGV2YRGCSHT2YWBAVFTLIHZT2F3WRPIBC3EQQBB7UFY65F6447QXW3JSZQRB62S4UYFPIL2IQO2EY',
        firstName: 'John',
        lastName: 'Doe',
        patronymic: null,
        projects_attempts: 3,
        auctions_attempts: 7,
        payment_start: DateTime.now(),
        payment_end: DateTime.now().plus({ days: 30 }),
        planId: 1,
        emailVerifiedAt: DateTime.now(),
        bornAt: null,
      },
      {
        email: 'example2@example.com',
        selectedProfileId: null,
        password: 'password2',
        secret: 'GHKDVOUYJV3OMJVVSIUTIF2RLXGFMPLCY6UPYRKHUZYAATXLQXXTFNRWFZPJQ22KHFEYWBWDPYIPSM4OKY73PKR63GUPX2ATSJLCV3Y',
        firstName: 'Jane',
        lastName: 'Smith',
        patronymic: null,
        projects_attempts: 5,
        auctions_attempts: 15,
        payment_start: DateTime.now(),
        payment_end: DateTime.now().plus({ days: 30 }),
        planId: 4,
        emailVerifiedAt: DateTime.now(),
        bornAt: null,
      },
      {
        email: 'example3@example.com',
        selectedProfileId: null,
        password: 'password3',
        secret: '3F4SSLENLAUCN7TD7CKDR3K2ZUGNFHFWLVIHUUMESRU7JB5LIKTNDBZUDU2RVHLWGS5QGE4D3BYQW6DQFVZRP2G3OTU24DUVPU6MFXI',
        firstName: 'Alex',
        lastName: 'Johnson',
        patronymic: null,
        projects_attempts: 9,
        auctions_attempts: 21,
        payment_start: DateTime.now(),
        payment_end: DateTime.now().plus({ days: 90 }),
        planId: 2,
        emailVerifiedAt: DateTime.now(),
        bornAt: null,
      },
      {
        email: 'example4@example.com',
        selectedProfileId: null,
        password: 'password4',
        secret: 'SQW3333TZ2UMOETDXLSQMYS3PINPHHGPZXZSHUT6O6H4TY6H5OFRH2FEBGKGR7OBMKVN3AJBXA7AF2F6ACYP7IUYUI6I3JTQE64R7EI',
        firstName: 'Michael',
        lastName: 'Brown',
        patronymic: null,
        projects_attempts: 1,
        auctions_attempts: 1,
        emailVerifiedAt: DateTime.now(),
        bornAt: null,
      },
      {
        email: 'example5@example.com',
        selectedProfileId: null,
        password: 'password5',
        secret: 'TVO4YYJ74B3CYDLJZWZQ7JB7LBOGAFN7WP3NUUVHDBOYOY7IXCUGEIGLTMLABALUEDEQ4EAL3QYOESGPXABRLW7OUKUQCDZE7JGFCEQ',
        firstName: 'Ernest',
        lastName: 'Gray',
        patronymic: null,
        projects_attempts: 10000,
        auctions_attempts: 10000,
        payment_start: DateTime.now(),
        payment_end: DateTime.now().plus({ days: 365 }),
        planId: 8,
        emailVerifiedAt: DateTime.now(),
        bornAt: null,
      },
      {
        email: 'example6@example.com',
        selectedProfileId: null,
        password: 'password5',
        secret: 'JXPNRXUTJMBDEBR4V27KHVPSVWYAUYOBROSCVPL2ZC4GQHOWD7ATXKBNAIGUTYYT2O35QVGF5UXAM2RSMOLEWYTWRI6AO42R2QBWCJY',
        firstName: 'Emma',
        lastName: 'Wilson',
        patronymic: null,
        projects_attempts: 10000,
        auctions_attempts: 10000,
        payment_start: DateTime.now(),
        payment_end: DateTime.now().plus({ days: 365 }),
        planId: 8,
        emailVerifiedAt: DateTime.now(),
        bornAt: null,
      },
      {
        email: 'example7@example.com',
        selectedProfileId: null,
        password: 'password6',
        secret: 'ZMKJZXNQC7AAHZK4S6EQTPOTNCCEU36PEMJR4ABDK6F443AKD3LLFEOTOFAKXDGNSZ23SGXUK74MIBQMUDEYHJNSDATLSDKBZFGFVBY',
        firstName: 'Oliver',
        lastName: 'Wilson',
        patronymic: null,
        projects_attempts: 10000,
        auctions_attempts: 10000,
        payment_start: DateTime.now(),
        payment_end: DateTime.now().plus({ days: 365 }),
        planId: 8,
        emailVerifiedAt: DateTime.now(),
        bornAt: null,
      },
      {
        email: 'example8@example.com',
        selectedProfileId: null,
        password: 'password7',
        secret: 'A5QR6MFEQ3SI7NWZZB3P3IVEZR353M65UU7ROW5SESICGACNNG6SA5VTH6KOTWBET3FVUJZJ22PJUPQGTAMU4KX34KOYYKITZKZAK2A',
        firstName: 'Sophia',
        lastName: 'Adams',
        patronymic: null,
        projects_attempts: 10000,
        auctions_attempts: 10000,
        payment_start: DateTime.now(),
        payment_end: DateTime.now().plus({ days: 365 }),
        planId: 8,
        emailVerifiedAt: DateTime.now(),
        bornAt: null,
      },
      {
        email: 'example9@example.com',
        selectedProfileId: null,
        password: 'password8',
        secret: 'VCXIIRQYQMITMAVKMLEFO56BRUFULWSDOASFRT2Y4HK24HGKPZWT47CPQ7GEVK73GTIQ6J6GVVZJZXT7QJU5SAHUGL4AP43CNGGYFFY',
        firstName: 'David',
        lastName: 'Lee',
        patronymic: null,
        projects_attempts: 10000,
        auctions_attempts: 10000,
        payment_start: DateTime.now(),
        payment_end: DateTime.now().plus({ days: 365 }),
        planId: 8,
        emailVerifiedAt: DateTime.now(),
        bornAt: null,
      },
    ])
  }
}
