import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Profile from '../../app/Models/Profile'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  public static environment = ['development']
  public async run () {
    await Profile.createMany([
      {
        userId: 1,
        displayName: 'Software Developer',
        description: 'Creating websites',
        location: 'New York',
        industry: 'Technology',
        ownedIntellectualResources: null,
        ownedMaterialResources: null,
        tin: '123456789101',
        performance: null,
        legalStructure: null,
        views: 10,
        isVisible: true,
        isPersonal: true,
        avatar: null,
        instagramUrl: null,
        whatsappUrl: null,
        websiteUrl: 'https://limpid.kz/',
        telegramUrl: null,
        twoGisUrl: 'https://2gis.kz/astana',
        tinVerifiedAt: DateTime.now(),
      },
      {
        userId: 2,
        displayName: 'Graphic Designer',
        description: 'Creating design for different spheres',
        location: 'London',
        industry: 'Design',
        ownedIntellectualResources: 'Ideas for design',
        ownedMaterialResources: 'Office',
        tin: '987654321',
        performance: null,
        legalStructure: null,
        views: 5,
        isVisible: true,
        isPersonal: true,
        avatar: null,
        instagramUrl: null,
        whatsappUrl: null,
        websiteUrl: null,
        telegramUrl: null,
        twoGisUrl: null,
        tinVerifiedAt: null,
      },
      {
        userId: 3,
        displayName: 'Marketing Specialist',
        description: 'Analyzing the market',
        location: 'London',
        industry: 'Marketing',
        ownedIntellectualResources: null,
        ownedMaterialResources: null,
        performance: null,
        legalStructure: null,
        views: 5,
        isVisible: true,
        isPersonal: true,
        avatar: null,
        instagramUrl: null,
        whatsappUrl: null,
        websiteUrl: null,
        telegramUrl: null,
        twoGisUrl: null,
        tinVerifiedAt: null,
      },
      {
        userId: 4,
        displayName: 'Photographer',
        description: 'Creating new stylish views',
        location: 'London',
        industry: 'Photography',
        ownedIntellectualResources: null,
        ownedMaterialResources: 'Camera',
        performance: null,
        legalStructure: null,
        views: 6,
        isVisible: true,
        isPersonal: true,
        avatar: null,
        instagramUrl: 'https://www.instagram.com/',
        whatsappUrl: null,
        websiteUrl: null,
        telegramUrl: null,
        twoGisUrl: null,
        tinVerifiedAt: null,
      },
      {
        userId: 5,
        displayName: 'Consultant',
        description: 'Making various solutions',
        location: 'Sydney',
        industry: 'Consulting',
        ownedIntellectualResources: null,
        ownedMaterialResources: 'Office',
        performance: null,
        legalStructure: null,
        views: 2,
        isVisible: true,
        isPersonal: true,
        avatar: null,
        instagramUrl: null,
        whatsappUrl: null,
        websiteUrl: null,
        telegramUrl: null,
        twoGisUrl: null,
        tinVerifiedAt: null,
      },
      {
        userId: 6,
        displayName: 'Interior Designer',
        description: 'Excellent designer',
        location: 'Berlin',
        industry: 'Design',
        ownedIntellectualResources: 'Ideas',
        ownedMaterialResources: null,
        performance: null,
        legalStructure: null,
        views: 25,
        isVisible: true,
        isPersonal: true,
        avatar: null,
        instagramUrl: null,
        whatsappUrl: null,
        websiteUrl: null,
        telegramUrl: 'https://2gis.kz/astana',
        twoGisUrl: 'https://2gis.kz/astana',
        tinVerifiedAt: null,
      },
      {
        userId: 7,
        displayName: 'Financial Analyst',
        description: 'Working in Finance Strategy',
        location: 'Toronto',
        industry: 'Finance',
        ownedIntellectualResources: null,
        ownedMaterialResources: null,
        performance: null,
        legalStructure: null,
        views: 17,
        isVisible: true,
        isPersonal: true,
        avatar: null,
        instagramUrl: 'https://limpid.kz/',
        whatsappUrl: 'https://limpid.kz/',
        websiteUrl: null,
        telegramUrl: 'https://limpid.kz/',
        twoGisUrl: null,
        tinVerifiedAt: null,
      },
      {
        userId: 8,
        displayName: 'Writer',
        description: 'Currently working on shoer stories',
        location: 'Almaty',
        industry: 'Writing',
        ownedIntellectualResources: null,
        ownedMaterialResources: 'Writing machine',
        performance: null,
        legalStructure: null,
        views: 5,
        isVisible: true,
        isPersonal: true,
        avatar: null,
        instagramUrl: null,
        whatsappUrl: 'https://limpid.kz/',
        websiteUrl: null,
        telegramUrl: null,
        twoGisUrl: null,
        tinVerifiedAt: null,
      },
      {
        userId: 9,
        displayName: 'Architect',
        description: 'Creating and thinking on all things',
        location: 'Tokyo',
        industry: 'Architecture',
        ownedIntellectualResources: null,
        ownedMaterialResources: null,
        performance: null,
        legalStructure: null,
        views: 5,
        isVisible: true,
        isPersonal: true,
        avatar: null,
        instagramUrl: 'https://limpid.kz/',
        whatsappUrl: 'https://limpid.kz/',
        websiteUrl: 'https://limpid.kz/',
        telegramUrl: 'https://limpid.kz/',
        twoGisUrl: 'https://limpid.kz/',
        tinVerifiedAt: null,
      },
    ])
  }
}
