import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Tender from '../../app/Models/Tender'
import { Duration, DateTime } from 'luxon'

export default class extends BaseSeeder {
  public static environment = ['development']
  public async run() {
    const duration = 'P20D'
    await Tender.createMany([
      {
        profileId: 1,
        wonTenderBidId: null,
        title: 'Construction Project Tender',
        description: 'Seeking contractors for a construction project',
        industry: 'Construction',
        startingPrice: 3600,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: DateTime.now(),
      },
      {
        profileId: 1,
        wonTenderBidId: null,
        title: 'IT Services Tender',
        description: 'Requesting proposals for IT services',
        industry: 'Technology',
        startingPrice: 10000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: null,
      },
      {
        profileId: 2,
        wonTenderBidId: null,
        title: 'Marketing Campaign Tender',
        description: 'Looking for agencies to handle a marketing campaign',
        industry: 'Marketing',
        startingPrice: 5000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: DateTime.now(),
      },
      {
        profileId: 2,
        wonTenderBidId: null,
        title: 'Supply Chain Tender',
        description: 'Procuring suppliers for a manufacturing company',
        industry: 'Manufacturing',
        startingPrice: null,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: null,
      },
      {
        profileId: 3,
        wonTenderBidId: null,
        title: 'Consulting Services Tender',
        description: 'Inviting bids for consulting services',
        industry: 'Consulting',
        startingPrice: 2000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: DateTime.now(),
      },
      {
        profileId: 3,
        wonTenderBidId: null,
        title: 'Event Management Tender',
        description: 'Organizing a large-scale event and seeking event management services',
        industry: 'Event Management',
        startingPrice: 15000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: null,
      },
      {
        profileId: 4,
        wonTenderBidId: null,
        title: 'Graphic Design Tender',
        description: 'Hiring graphic designers for a creative project',
        industry: 'Design',
        startingPrice: null,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: DateTime.now(),
      },
      {
        profileId: 4,
        wonTenderBidId: null,
        title: 'Logistics Services Tender',
        description: 'Requesting logistics services for transportation and delivery',
        industry: 'Logistics',
        startingPrice: 5000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: null,
      },
      {
        profileId: 5,
        wonTenderBidId: null,
        title: 'Software Development Tender',
        description: 'Seeking software development services for a custom application',
        industry: 'Technology',
        startingPrice: 20000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: DateTime.now(),
      },
      {
        profileId: 5,
        wonTenderBidId: null,
        title: 'Consulting Services Tender',
        description: 'Requesting consulting services for business strategy development',
        industry: 'Consulting',
        startingPrice: 8000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: null,
      },
      {
        profileId: 6,
        wonTenderBidId: null,
        title: 'Marketing Campaign Tender',
        description: 'Launching a marketing campaign for a new product',
        industry: 'Marketing',
        startingPrice: 10000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: DateTime.now(),
      },
      {
        profileId: 6,
        wonTenderBidId: null,
        title: 'Architectural Design Tender',
        description: 'Seeking architectural design services for a residential project',
        industry: 'Architecture',
        startingPrice: 20000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: null,
      },
      {
        profileId: 7,
        wonTenderBidId: null,
        title: 'Translation Services Tender',
        description: 'Requesting translation services for a set of documents',
        industry: 'Translation',
        startingPrice: 5000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: DateTime.now(),
      },
      {
        profileId: 7,
        wonTenderBidId: null,
        title: 'Interior Design Tender',
        description: 'Hiring interior designers for a commercial space',
        industry: 'Interior Design',
        startingPrice: 15000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: null,
      },
      {
        profileId: 8,
        wonTenderBidId: null,
        title: 'Legal Services Tender',
        description: 'Requesting legal services for contract review and consultation',
        industry: 'Legal',
        startingPrice: 8000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: DateTime.now(),
      },
      {
        profileId: 8,
        wonTenderBidId: null,
        title: 'Event Catering Tender',
        description: 'Seeking event catering services for a corporate event',
        industry: 'Catering',
        startingPrice: 10000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: null,
      },
      {
        profileId: 9,
        wonTenderBidId: null,
        title: 'IT Support Tender',
        description: 'Hiring IT support services for network infrastructure setup',
        industry: 'IT',
        startingPrice: 5000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: DateTime.now(),
      },
      {
        profileId: 9,
        wonTenderBidId: null,
        title: 'Photography Services Tender',
        description: 'Requesting professional photography services for an event',
        industry: 'Photography',
        startingPrice: 3000,
        purchaseType: 'Open',
        duration: Duration.fromISO(duration),
        verifiedAt: null,
      },
    ])
  }
}
