services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - .:/api
    ports:
      - 3000:3000
      - 5555:5555
    entrypoint:
      - sleep
      - infinity
