version: '3.9'
volumes:
  mysql:
  redis:
services:
  mysql:
    image: mysql:8.0.32
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - ${MYSQL_PORT}
  redis:
    image: 'redis:7.0.10-alpine'
    volumes:
      - redis:/data
    expose:
      - ${REDIS_PORT}
  api:
    build: .
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    ports:
      - 127.0.0.1:3001:${PORT}
