version: "3.9"
networks:
  mysql:
  redis:
volumes:
  mysql:
  redis:
services:
  mysql:
    image: mysql:8.0.32
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - mysql
    expose:
      - ${MYSQL_PORT}
  redis:
    image: "redis:7.0.10-alpine"
    volumes:
      - redis:/data
    networks:
      - redis
    expose:
      - ${REDIS_PORT}
  api:
    build: .
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    networks:
      - mysql
      - redis
    ports:
      - 127.0.0.1:3001:${PORT}
