openapi: 3.0.0
info:
  title: api.limpid.kz
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:3333'
  - url: 'https://api.limpid.kz'
tags:
  - name: User
  - name: Users
  - name: Session
  - name: Email verification
  - name: Password recovery
  - name: Profiles
security:
  - bearerAuth: []
paths:
  /users:
    post:
      tags:
        - Users
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - email
                - password
                - first_name
                - last_name
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
      responses:
        '201':
          description: User is created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'
  /session:
    post:
      tags:
        - Session
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User is logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                      token:
                        type: string
                      expires_at:
                        type: string
    delete:
      tags:
        - Session
      responses:
        '204':
          description: User is logged out
  /email-verification:
    post:
      tags:
        - Email verification
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
      responses:
        '201':
          description: User email verification mail send
    patch:
      tags:
        - Email verification
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - email
                - token
              properties:
                email:
                  type: string
                token:
                  type: string
      responses:
        '204':
          description: User email verified
  /password-recovery:
    post:
      tags:
        - Password recovery
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
      responses:
        '201':
          description: Password recovery mail send
    patch:
      tags:
        - Password recovery
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - email
                - password
                - token
              properties:
                email:
                  type: string
                password:
                  type: string
                token:
                  type: string
      responses:
        '204':
          description: User's password is changed
  /user:
    get:
      tags:
        - User
      responses:
        '200':
          description: User data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'
    patch:
      tags:
        - User
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: 
                    - string
                    - 'null'
                password:
                  type: 
                    - string
                    - 'null'
                first_name:
                  type: 
                    - string
                    - 'null'
                last_name:
                  type: 
                    - string
                    - 'null'
                patronymic:
                  type: 
                    - string
                    - 'null'
                born_at:
                  type: 
                    - string
                    - 'null'
                selected_profile_id:
                  type: 
                    - integer
                    - 'null'
      responses:
        '200':
          description: Updated user's data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'
  /profiles:
    get:
      tags:
        - Profiles
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
        - in: query
          name: per_page
          required: false
          schema:
            type: integer
        - in: query
          name: user_id
          required: false
          schema:
            type: integer
        - in: query
          name: industry
          required: false
          schema:
            type: string
        - in: query
          name: search
          required: false
          schema:
            type: string
      responses:
        '200':
          description: User's profiles
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      per_page:
                        type: integer
                      current_page:
                        type: integer
                      last_page:
                        type: integer
                      first_page:
                        type: integer
                      first_page_url:
                        type: string
                      last_page_url:
                        type: string
                      next_page_url:
                        type: string
                      previous_page_url:
                        type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Profile'
    post:
      tags:
        - Profiles
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - display_name
                - description
                - location
                - industry
                - tin
                - is_visible
              properties:
                display_name:
                  type: string
                description:
                  type: string
                location:
                  type: string
                industry:
                  type: string
                owned_intellectual_resources:
                  type: string
                owned_material_resources:
                  type: string
                tin:
                  type: string
                is_visible:
                  type: boolean
                avatar:
                  type: string
                  format: binary
      responses:
        '201':
          description: Profile is created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Profile'
  /profiles/{profile_id}:
    get:
      tags:
        - Profiles
      parameters:
        - in: path
          name: profile_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Profile data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Profile'
    patch:
      tags:
        - Profiles
      parameters:
        - in: path
          name: profile_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                display_name:
                  type: string
                description:
                  type: string
                location:
                  type: string
                industry:
                  type: string
                owned_intellectual_resources:
                  type: string
                owned_material_resources:
                  type: string
                tin:
                  type: string
                is_visible:
                  type: boolean
                avatar:
                  type: string
                  format: binary
      responses:
        '200':
          description: Updated profile's data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Profile'
    delete:
      tags:
        - Profiles
      parameters:
        - in: path
          name: profile_id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Profile is deleted
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        selected_profile_id:
          type:
            - integer
            - 'null'
        first_name:
          type: string
        last_name:
          type: string
        patronymic:
          type:
            - string
            - 'null'
        email_verified_at:
          type:
            - string
            - 'null'
        born_at:
          type:
            - string
            - 'null'
        created_at:
          type: string
        updated_at:
          type: string
    Profile:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        display_name:
          type: string
        description:
          type: string
        location:
          type: string
        industry:
          type: string
        owned_intellectual_resources:
          type:
            - string
            - 'null'
        owned_material_resources:
          type:
            - string
            - 'null'
        tin:
          type: string
        legal_structure:
          type:
            - string
            - 'null'
        is_visible:
          type: boolean
        is_personal:
          type: boolean
        avatar:
          $ref: '#/components/schemas/Attachment'
        tin_verified_at:
          type:
            - string
            - 'null'
        created_at:
          type: string
        updated_at:
          type: string
    Attachment:
      type: object
      properties:
        url:
          type:
            - string
            - 'null'
        name:
          type:
            - string
            - 'null'
        size:
          type: string
        extname:
          type: string
        mimeType:
          type: string
